# Vibrant Modern Dark Theme
# A vibrant, high-contrast dark theme with modern GitHub-inspired colors
#
# name: Vibrant Modern Dark
# author: Saurabh
# description: A vibrant dark theme with modern colors and high contrast for excellent readability

[colors.bright]
black = "#2d333b"
blue = "#58a6ff"
cyan = "#39c5cf"
green = "#3bce9d"
magenta = "#d2a8ff"
red = "#ff7b72"
white = "#ffffff"
yellow = "#e3b341"

[colors.cursor]
cursor = "#2ea4ad"
text = "#0d1117"

[colors.hints.end]
background = "#0d1117"
foreground = "#2ea4ad"

[colors.hints.start]
background = "#2ea4ad"
foreground = "#0d1117"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#161b22"
blue = "#1f6feb"
cyan = "#2ea4ad"
green = "#26a869"
magenta = "#c770f0"
red = "#f85149"
white = "#f0f0f0"
yellow = "#c69026"

[colors.primary]
background = "#0d1117"
bright_foreground = "#ffffff"
foreground = "#f0f0f0"
dim_foreground = "#c9c9c9"

[colors.search.focused_match]
background = "#c770f0"
foreground = "#0d1117"

[colors.search.matches]
background = "#2ea043"
foreground = "#0d1117"

[colors.selection]
background = "#1158c7"
text = "#f0f0f0"

[colors.vi_mode_cursor]
cursor = "#c770f0"
text = "#0d1117"

# Enhanced indexed colors for better terminal app support
[[colors.indexed_colors]]
index = 16
color = "#2188ff"

[[colors.indexed_colors]]
index = 17
color = "#a371f7"

[[colors.indexed_colors]]
index = 18
color = "#2ea043"

[[colors.indexed_colors]]
index = 19
color = "#f0883e"

[[colors.indexed_colors]]
index = 20
color = "#1e4273"

[[colors.indexed_colors]]
index = 21
color = "#fc55d3"
