# Enhanced Professional Cyberpunk Theme
# A modern take on the classic cyberpunk aesthetic with improved readability
#
# name: Professional Cyberpunk
# author: Saurabh
# description: A modern cyberpunk theme with enhanced readability and professional aesthetics

[colors.bright]
black = "#29293f"
blue = "#67d3ff"
cyan = "#5df8ff"
green = "#72ffd0"
magenta = "#fc75ea"
red = "#ff5286"
white = "#ffffff"
yellow = "#fef26c"

[colors.cursor]
cursor = "#00ff9f"
text = "#0a0a16"

[colors.hints.end]
background = "#0a0a16"
foreground = "#00ff9f"

[colors.hints.start]
background = "#00ff9f"
foreground = "#0a0a16"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#151528"
blue = "#00bfff"
cyan = "#00faff"
green = "#00ff9f"
magenta = "#fb33db"
red = "#ff2e6d"
white = "#f0f0f0"
yellow = "#fcee54"

[colors.primary]
background = "#0c0c1d"
bright_foreground = "#ffffff"
foreground = "#f0f0f0"
dim_foreground = "#c9c9c9"

[colors.search.focused_match]
background = "#fc00ff"
foreground = "#0a0a16"

[colors.search.matches]
background = "#00ff9f"
foreground = "#0a0a16"

[colors.selection]
background = "#fc28a8"
text = "#0a0a16"

[colors.vi_mode_cursor]
cursor = "#fc00ff"
text = "#0a0a16"

# Enhanced indexed colors for better terminal app support
[[colors.indexed_colors]]
index = 16
color = "#3b79c7"

[[colors.indexed_colors]]
index = 17
color = "#7d4cdb"

[[colors.indexed_colors]]
index = 18
color = "#36c98d"

[[colors.indexed_colors]]
index = 19
color = "#ff9b50"

[[colors.indexed_colors]]
index = 20
color = "#2c3e50"

[[colors.indexed_colors]]
index = 21
color = "#e84393"
